### ISSUE TITLE
phono3py entry point breaks naming convention

### ISSUE THREAD

**Issue by ltalirz** [aiida-phonopy/aiida-phonopy#10]
I notice that the phono3py entry point breaks the naming convention that entry points provided by a plugin should start with the name of the plugin.
https://travis-ci.org/aiidateam/aiida-registry/jobs/591463873#L356

This may be a bit of a special case but it may still be worth renaming it to follow the standard...

**Comment by atztogo** [comment]
Thanks. phono3py entry point was removed.

**Comment by ltalirz** [comment]
great!
