### ISSUE TITLE
please update trove classifiers

### ISSUE THREAD

**Issue by ltalirz** [aiida-phonopy/aiida-phonopy#14]
please add the `Framework :: AiiDA` classifier and update the python language classifier (currently suggests that this plugin supports only python 3.5).

**Comment by atztogo** [comment]
Thanks. Now I have done it. I hope it is properly done.
https://github.com/aiida-phonopy/aiida-phonopy/blob/develop/setup.json

**Comment by ltalirz** [comment]
great, thanks Togo!
