### ISSUE TITLE
replace 'requires' by 'install_requires' in setup.json

### ISSUE THREAD

**Issue by ltalirz** [aiida-phonopy/aiida-phonopy#5]
I believe this was meant to say 'install_requires':
https://github.com/aiida-phonopy/aiida-phonopy/blob/d27b378e17ec335f46a8554380083a2ce7a1141e/setup.json#L8

Also, it would make sense to add the appropriate version of `aiida-core` to the requirements.

**Comment by abelcarreras** [comment]
done
