### ISSUE TITLE
please add aiida-core as dependency

### ISSUE THREAD

**Issue by ltalirz** [aiida-phonopy/aiida-phonopy#9]
aiida-core should be specified as a dependency in setup.json

depending on the aiida version, consider something like
```
aiida-core>=0.12.3,<1.0.0
```
or
```
aiida-core>=1.0.0b6,<2.0.0
```

**Comment by atztogo** [comment]
Thanks. This has been done.

**Comment by ltalirz** [comment]
thanks!
